### PR TITLE
Build.prop Mods + screenrecorder: Do some prereq's before showing options

### PR DESCRIPTION
**Pull request by ghost**
-Settings for phones will not be shown for non-phones.

-Devices without a proximity sensor will not be shown options
for proximity.

-Devices that have phone capabilities and a proximity sensor should
see no change.

### CODE REVIEW

**Comment by scotthartbti** [comment]
Cool, I'll check this out in later this evening.

**Comment by ghost** [comment]
Hey Scott,

This is not really an issue at all. I thought just thought it would add some logical consistency. I haven't tested this on a device that has phone capabilities but logically it should be right...

Just a note: I couldn't remove the items using "prefset". I had to get the PreferenceCategory and use it to remove the individual settings... ;)

Thanks

**Comment by scotthartbti** [comment]
good deal.  Thanks.

**Comment by ghost** [comment]
Is this not the sort of stuff that you want to put in your ROM? It's totally cool if not. I'd just like to know so I don't spend time on stuff that's not going to get used. I know you're busy... Let me know ;)

BTW, I'm feeling much better about git. I think what I'll do is:
1. git pull
2. git branch dev
3. git checkout dev
4. _make changes/test, commit them_
5. git checkout kk44
6. git pull (update remote changes while working)
7. git cherry-pick (all my dev branch change commits )
8. git push

**Comment by scotthartbti** [comment]
Yea thats cool...  that can be your first one once i get you added.  ran
out of time last night... started working on modifying the slim pie commits
for my build and before you I knew it, the time was 3 AM..  Anyways, Im not
looking for anything specific or expecting anything in particular, just
figure if you find anything thats out of place or see something that would
better things or new features, go ahead and add it.

But yea that process seems fine.  And like i said before, if your not
currently up to date with my branch or something is different, git is going
to tell you so its like an extra reminder that you forgot to pull the
current repo changes first and if that does happen, the only way to
actually push the changes is by issuing the -f (force) flag... so yea...
dont do that.  lol.  Ill get you added her at some point.

**Comment by ghost** [comment]
I redid these commits to get the repo up to date so I'll close this and submit them. Note to self (Never use force!)

**Pull request closed without merging**
