### PR TITLE
Home button to wake / Materialize Beanstalk options icon

### PR DESCRIPTION
**Pull request by sileshn**
http://i.imgur.com/auwh9Pa.png

http://i.imgur.com/auwh9Pa.png

### CODE REVIEW

**Comment by sileshn** [comment]
http://i.imgur.com/NdUqL2b.png

**Comment by scotthartbti** [comment]
Just saw this.  I'll merge it in later today.  Thanks for the help.

**Comment by sileshn** [comment]
No problem.

**Comment by scotthartbti** [comment]
skipped home button wake commit as that was recently added.

commit f5247422efb44215fdb001f1b598c3f436652920 for options icon.  Thanks again.

**Comment by sileshn** [comment]
Pleased to be of some help.

**Pull request closed without merging**
