### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by spezi77**

### CODE REVIEW

**Comment by scotthartbti** [comment]
Closed?

**Comment by spezi77** [comment]
Ya, give me a minute to push new commits. While testing I discovered untranslated stuff. ;)
Will 6.09 be arriving this weekend?

**Comment by scotthartbti** [comment]
Yea... When I get a chance... Been a lot going on here and free time is a
little limited.

**Comment by spezi77** [comment]
Yea, same situation over here.
Pushing my changes now.. upload speed is miserable today :/

**Pull request closed without merging**
