### PR TITLE
fix: 'display and animations' FC

### PR DESCRIPTION
**Pull request by ghost**
-Seems like there was an incorrect operator on line 51 in
ScreenAndAnimations.java. Also added additional null checks
incase preference screen is removed

-Seems like a typo in beanstalk_interface_settings.xml?

Change-Id: Ia8052bfac213297b82a8d28d5f5e7cc4b1880cbc

### CODE REVIEW

**Comment by ghost** [comment]
I'm new to this so I apologize if I didn't follow the correct procedure. I build your rom for the YP-G70 ( venturi ) and when ever I try to open "Display and animations" from the "Beanstalk options" in Settings I get a force close. It seems that problem is really line 52 in ScreenAndAnimations.java which removes the PreferenceScreen then mListViewAnimation and mListViewInterpolator  end up being null; causing the FC.... Perhaps changing the operator was not the correct way to fix the issue but I all the options seem to work with the exception of the CRT animations. No matter what I choose there CRT remains horizontal...

**Comment by scotthartbti** [comment]
Hmm...  odd...  I dont get a force close at all and havent since day 1...

**Comment by scotthartbti** [comment]
Can you provide a log cat of what your seeing?

**Comment by ghost** [comment]
Sure would you like a full logcat or truncated?

**Comment by scotthartbti** [comment]
Just the relevant part if possible.

**Comment by scotthartbti** [comment]
And as for following correct procedure, this is perfectly fine and honestly what i prefer.  I dont really check XDA at all so if there are issues that need to be addressed this is the perfect way to let me know about it.

**Comment by ghost** [comment]
E/AndroidRuntime(  637): FATAL EXCEPTION: main
E/AndroidRuntime(  637): Process: com.android.settings, PID: 637
E/AndroidRuntime(  637): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException
E/AndroidRuntime(  637):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2227)
E/AndroidRuntime(  637):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2277)
E/AndroidRuntime(  637):    at android.app.ActivityThread.access$800(ActivityThread.java:145)
E/AndroidRuntime(  637):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
E/AndroidRuntime(  637):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(  637):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(  637):    at android.app.ActivityThread.main(ActivityThread.java:5088)
E/AndroidRuntime(  637):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  637):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(  637):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime(  637):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime(  637):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(  637): Caused by: java.lang.NullPointerException
E/AndroidRuntime(  637):    at com.android.settings.beanstalk.ScreenAndAnimations.onCreate(ScreenAndAnimations.java:58)
E/AndroidRuntime(  637):    at android.app.Fragment.performCreate(Fragment.java:1678)
E/AndroidRuntime(  637):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
E/AndroidRuntime(  637):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
E/AndroidRuntime(  637):    at android.app.BackStackRecord.run(BackStackRecord.java:684)
E/AndroidRuntime(  637):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
E/AndroidRuntime(  637):    at android.app.Activity.performStart(Activity.java:5374)
E/AndroidRuntime(  637):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
E/AndroidRuntime(  637):    ... 11 more
W/ActivityManager(  498):   Force finishing activity com.android.settings/.SubSettings
W/ActivityManager(  498):   Force finishing activity com.android.settings/.SubSettings

**Comment by ghost** [comment]
@deedwar who is building your rom for the "Sony Xperia Acro S" ( I think ) told me he was having a similar/the same issue....

EDIT: Yes it looks like he is having the same issue too - http://forum.xda-developers.com/showpost.php?p=49975339&postcount=1184

**Comment by deedwar** [comment]
I was having the same issue and i just cherry-picked this commit and it has fixed the issue.  Thanks for the help @Meticulus

**Comment by ghost** [comment]
Glad I could help!

**Comment by scotthartbti** [comment]
Gotta love android devices.... Works on 90% of devices and then crashes on
the other 10%... Frustrating at times.  I'll take a closer look and merge
it if it pans out

**Comment by ghost** [comment]
Thanks for all the hard work. Love the ROM! Let me know if you need anything...

**Comment by scotthartbti** [comment]
Thanks for your contribution.  Commit 23a5414fb213dc6b838f3c5cbe1e79a2b6f06e0f has been added.

**Pull request closed without merging**
