### PR TITLE
Translate complete Beanstalk settings to German

### PR DESCRIPTION
**Pull request by ghost**
All strings from Beanstalk settings are in German now.

### CODE REVIEW

**Comment by ghost** [comment]
Hello?
Translation took 2 hours. So please merge it.

**Comment by ghost** [comment]
**Hello!!!**

**Comment by scotthartbti** [comment]
Been a bit hectic.  Thanks for your patience.

**Comment by ghost** [comment]
Sorry, next time I will wait :+1:

**Comment by scotthartbti** [comment]
No worries.  Thanks for the contribution.

**Pull request merged**
